Remove update_flavor method from compute
update_flavor API is not supported by nova and raises
HttpException: Bad Request if called from openstacksdk,
hence removed this method to cleanup the source code.

Closes-Bug: 1563235
Change-Id: I1c54d0afcd8b49cac9d7342e466e6636b5c599f1