Reverse order of tests to avoid incompatibility
If py26 tests are run first, there is some incompatibility in the
.testrepository that breaks several tests.  To get around this, you
need to run the py33 tests first.  This change was made over in the
cliff project.

Before:

    (.venv)terry@brat:~/hp/sdk$ rm -rf .testrepository/
    (.venv)terry@brat:~/hp/sdk$ tox
      ...
      py26: commands succeeded
      py27: commands succeeded
    ERROR:   py33: commands failed
    ERROR:   py34: commands failed
    ERROR:   pypy: commands failed
      pep8: commands succeeded

After:

    (.venv)terry@brat:~/hp/sdk$ rm -rf .testrepository/
    (.venv)terry@brat:~/hp/sdk$ tox
      ...
      py33: commands succeeded
      py34: commands succeeded
      py26: commands succeeded
      py27: commands succeeded
      pypy: commands succeeded
      pep8: commands succeeded
      congratulations :)
    (.venv)terry@brat:~/hp/sdk$ 

Change-Id: I64925097ce003659c4daa0e105bd06dc30726921