exception: Correct argument
There were multiple calls to subclasses of 'SDKException' that were
providing a 'msg' kwarg. This doesn't exist. Instead, the parameter is
called 'message'. Correct this by using positional args instead.

Change-Id: Id425b9a57033c89b8a8466a32ab202cdf7556cb2
Signed-off-by: Stephen Finucane <stephenfin@redhat.com>