Fix TypeError in list_router_interfaces
It turns out, you can have a router object with a 'external_gateway_info'
key that is set to None. In that case, list_router_interfaces fail with

  File "../shade/openstackcloud.py", line 2624, in list_router_interfaces
    'external_fixed_ips' in router['external_gateway_info']):
TypeError: argument of type 'NoneType' is not iterable

How to repro
1) Create a router: neutron router-create foo
2) Run
import os_client_config, shade

cloud = os_client_config.make_shade(cloud='devstack')
router = cloud.get_router('foo')
cloud.list_router_interfaces(router, 'external')

Change-Id: I4c2894355958a7142670e186e7932048d66cfd59