stack event loops: handle get None result
We've seen at least one case in CI of `stack` being None when polling
for stack events:

    <snip>
      File "openstack/cloud/_orchestration.py", line 185, in delete_stack
        event_utils.poll_for_events(
      File "openstack/orchestration/util/event_utils.py", line 109,
      in poll_for_events
        stack_status = stack['stack_status']
    TypeError: 'NoneType' object is not subscriptable

Handle this case with a simple if.

Change-Id: Icce6e7b600125cf98e56d98e1c3df4177414398b