Display neutron api error message more precisely
When neutron-api response fails. Session object reports error as

    HttpException: Bad Request

and this cause lack of error information on openstack cli output.
buy the way neutron failure response body contains more informations

    {"NeutronError": {
	"message": "here is error message", "type": "HTTPBadRequest",
	"detail": ""}}

This changes raise exception with more precise error messages.

Change-Id: Ibea40e37ee6b6135f8b00c8a46e023ff59befd5b
Closes-Bug: 1633361